name: esa_gda_env
channels:
  - conda-forge
dependencies:
  - affine=2.4.0
  - annotated-types=0.7.0
  - aom=3.9.1
  - apng=0.3.4
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backcall=0.2.0
  - blosc=1.21.6
  - bokeh=3.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - capnproto=1.0.2
  - ceres-solver=2.2.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=4.5.0
  - charset-normalizer=3.4.3
  - click=8.1.8
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - comm=0.2.3
  - contourpy=1.3.0
  - coverage=7.10.4
  - cpd=0.5.5
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dask=2024.8.0
  - dask-core=2024.8.0
  - dask-expr=1.1.10
  - dataclasses=0.8
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - distributed=2024.8.0
  - draco=1.5.7
  - eigen=3.4.0
  - executing=2.2.0
  - exiv2=0.28.5
  - fgt=0.4.11
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.13.3
  - freexl=2.0.0
  - fsspec=2025.7.0
  - future=1.0.0
  - gdal=3.10.2
  - geos=3.13.0
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.0
  - glib-tools=2.84.0
  - glog=0.7.1
  - gmp=6.3.0
  - gsl=2.7
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.2.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - httplib2=0.22.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.12.0
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.15
  - kealib=1.6.1
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - laz-perf=3.4.0
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libamd=3.3.3
  - libarchive=3.7.7
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.25.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp17=17.0.6
  - libclang13=20.1.8
  - libcolamd=3.3.4
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxsparse=4.4.1
  - libcxx=20.1.8
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgdal=3.10.2
  - libgdal-arrow-parquet=3.10.2
  - libgdal-core=3.10.2
  - libgdal-fits=3.10.2
  - libgdal-grib=3.10.2
  - libgdal-hdf4=3.10.2
  - libgdal-hdf5=3.10.2
  - libgdal-jp2openjpeg=3.10.2
  - libgdal-kea=3.10.2
  - libgdal-netcdf=3.10.2
  - libgdal-pdf=3.10.2
  - libgdal-pg=3.10.2
  - libgdal-postgisraster=3.10.2
  - libgdal-tiledb=3.10.2
  - libgdal-xls=3.10.2
  - libgettextpo=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.67.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.0
  - libklu=2.3.5
  - libkml=1.3.0
  - liblapack=3.9.0
  - libldl=3.3.2
  - libllvm17=17.0.6
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libparquet=17.0.0
  - libparu=1.0.0
  - libpdal=2.8.4
  - libpdal-arrow=2.8.4
  - libpdal-core=2.8.4
  - libpdal-cpd=2.8.4
  - libpdal-draco=2.8.4
  - libpdal-e57=2.8.4
  - libpdal-hdf=2.8.4
  - libpdal-icebridge=2.8.4
  - libpdal-nitf=2.8.4
  - libpdal-pgpointcloud=2.8.4
  - libpdal-tiledb=2.8.4
  - libpdal-trajectory=2.8.4
  - libpmix=5.0.8
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.28.3
  - librbio=4.3.4
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libsuitesparseconfig=7.10.1
  - libtasn1=4.20.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libumfpack=6.3.5
  - libutf8proc=2.10.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - locket=1.0.0
  - lxml=6.0.0
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - metis=5.1.0
  - minizip=4.0.10
  - mock=5.2.0
  - morecantile=6.2.0
  - mpfr=4.2.1
  - mpi=1.0.1
  - msgpack-python=1.1.1
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - narwhals=2.1.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nitro=2.7.dev8
  - nose2=0.9.2
  - nspr=4.37
  - nss=3.115
  - numpy=2.0.2
  - opencl-headers=2025.06.13
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openmpi=5.0.8
  - openssl=3.5.2
  - orc=2.1.1
  - owslib=0.31.0
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - plotly=6.3.0
  - ply=3.11
  - poppler=24.12.0
  - poppler-data=0.4.12
  - postgresql=17.6
  - proj=9.5.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - psycopg2=2.9.10
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.7
  - pycparser=2.22
  - pydantic=2.0.3
  - pydantic-core=2.3.0
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebkit=5.15.9
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - qca=2.3.10
  - qgis=3.40.3
  - qhull=2020.2
  - qjson=0.9.0
  - qscintilla2=2.14.1
  - qt-main=5.15.15
  - qtkeychain=0.15.0
  - qtwebkit=5.212
  - qwt=6.3.0
  - rasterio=1.4.3
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.5
  - rio-cogeo=5.4.2
  - setuptools=80.9.0
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - spdlog=1.15.1
  - sqlite=3.50.4
  - stack_data=0.6.3
  - suitesparse=7.10.1
  - svt-av1=3.0.2
  - tblib=3.1.0
  - tiledb=2.27.2
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzcode=2025b
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x265=3.5
  - xarray=2024.7.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - anyio==4.10.0
      - boto3==1.42.10
      - botocore==1.42.10
      - cachetools==6.1.0
      - color-operations==0.2.0
      - exceptiongroup==1.3.0
      - geopandas==1.0.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jmespath==1.0.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - numexpr==2.10.2
      - pyogrio==0.11.1
      - pystac==1.10.1
      - rich==14.1.0
      - rio-tiler==7.8.1
      - s3transfer==0.16.0
      - shapely==2.0.7
      - sniffio==1.3.1
      - tqdm==4.67.1
      - urllib3==1.26.20
prefix: /Users/sofia/mambaforge/envs/esa_gda_env
